// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/helloworld.proto

package helloworld

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FirstNameRequest struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FirstNameRequest) Reset()         { *m = FirstNameRequest{} }
func (m *FirstNameRequest) String() string { return proto.CompactTextString(m) }
func (*FirstNameRequest) ProtoMessage()    {}
func (*FirstNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_helloworld_d130e9b83d1fb14f, []int{0}
}
func (m *FirstNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirstNameRequest.Unmarshal(m, b)
}
func (m *FirstNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirstNameRequest.Marshal(b, m, deterministic)
}
func (dst *FirstNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirstNameRequest.Merge(dst, src)
}
func (m *FirstNameRequest) XXX_Size() int {
	return xxx_messageInfo_FirstNameRequest.Size(m)
}
func (m *FirstNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FirstNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FirstNameRequest proto.InternalMessageInfo

func (m *FirstNameRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

type FirstNameReply struct {
	FirstNameReply       string   `protobuf:"bytes,1,opt,name=firstNameReply,proto3" json:"firstNameReply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FirstNameReply) Reset()         { *m = FirstNameReply{} }
func (m *FirstNameReply) String() string { return proto.CompactTextString(m) }
func (*FirstNameReply) ProtoMessage()    {}
func (*FirstNameReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_helloworld_d130e9b83d1fb14f, []int{1}
}
func (m *FirstNameReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirstNameReply.Unmarshal(m, b)
}
func (m *FirstNameReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirstNameReply.Marshal(b, m, deterministic)
}
func (dst *FirstNameReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirstNameReply.Merge(dst, src)
}
func (m *FirstNameReply) XXX_Size() int {
	return xxx_messageInfo_FirstNameReply.Size(m)
}
func (m *FirstNameReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FirstNameReply.DiscardUnknown(m)
}

var xxx_messageInfo_FirstNameReply proto.InternalMessageInfo

func (m *FirstNameReply) GetFirstNameReply() string {
	if m != nil {
		return m.FirstNameReply
	}
	return ""
}

type LastNameRequest struct {
	LastName             string   `protobuf:"bytes,1,opt,name=lastName,proto3" json:"lastName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LastNameRequest) Reset()         { *m = LastNameRequest{} }
func (m *LastNameRequest) String() string { return proto.CompactTextString(m) }
func (*LastNameRequest) ProtoMessage()    {}
func (*LastNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_helloworld_d130e9b83d1fb14f, []int{2}
}
func (m *LastNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastNameRequest.Unmarshal(m, b)
}
func (m *LastNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastNameRequest.Marshal(b, m, deterministic)
}
func (dst *LastNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastNameRequest.Merge(dst, src)
}
func (m *LastNameRequest) XXX_Size() int {
	return xxx_messageInfo_LastNameRequest.Size(m)
}
func (m *LastNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LastNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LastNameRequest proto.InternalMessageInfo

func (m *LastNameRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type LastNameReply struct {
	LastNameReply        string   `protobuf:"bytes,1,opt,name=lastNameReply,proto3" json:"lastNameReply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LastNameReply) Reset()         { *m = LastNameReply{} }
func (m *LastNameReply) String() string { return proto.CompactTextString(m) }
func (*LastNameReply) ProtoMessage()    {}
func (*LastNameReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_helloworld_d130e9b83d1fb14f, []int{3}
}
func (m *LastNameReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastNameReply.Unmarshal(m, b)
}
func (m *LastNameReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastNameReply.Marshal(b, m, deterministic)
}
func (dst *LastNameReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastNameReply.Merge(dst, src)
}
func (m *LastNameReply) XXX_Size() int {
	return xxx_messageInfo_LastNameReply.Size(m)
}
func (m *LastNameReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LastNameReply.DiscardUnknown(m)
}

var xxx_messageInfo_LastNameReply proto.InternalMessageInfo

func (m *LastNameReply) GetLastNameReply() string {
	if m != nil {
		return m.LastNameReply
	}
	return ""
}

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_helloworld_d130e9b83d1fb14f, []int{4}
}
func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (dst *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(dst, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_helloworld_d130e9b83d1fb14f, []int{5}
}
func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (dst *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(dst, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*FirstNameRequest)(nil), "helloworld.FirstNameRequest")
	proto.RegisterType((*FirstNameReply)(nil), "helloworld.FirstNameReply")
	proto.RegisterType((*LastNameRequest)(nil), "helloworld.LastNameRequest")
	proto.RegisterType((*LastNameReply)(nil), "helloworld.LastNameReply")
	proto.RegisterType((*HelloRequest)(nil), "helloworld.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "helloworld.HelloReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	GiveFirstName(ctx context.Context, in *FirstNameRequest, opts ...grpc.CallOption) (*FirstNameReply, error)
	GiveLastName(ctx context.Context, in *LastNameRequest, opts ...grpc.CallOption) (*LastNameReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GiveFirstName(ctx context.Context, in *FirstNameRequest, opts ...grpc.CallOption) (*FirstNameReply, error) {
	out := new(FirstNameReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/GiveFirstName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GiveLastName(ctx context.Context, in *LastNameRequest, opts ...grpc.CallOption) (*LastNameReply, error) {
	out := new(LastNameReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/GiveLastName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	GiveFirstName(context.Context, *FirstNameRequest) (*FirstNameReply, error)
	GiveLastName(context.Context, *LastNameRequest) (*LastNameReply, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GiveFirstName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FirstNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GiveFirstName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/GiveFirstName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GiveFirstName(ctx, req.(*FirstNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GiveLastName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LastNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GiveLastName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/GiveLastName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GiveLastName(ctx, req.(*LastNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
		{
			MethodName: "GiveFirstName",
			Handler:    _Greeter_GiveFirstName_Handler,
		},
		{
			MethodName: "GiveLastName",
			Handler:    _Greeter_GiveLastName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/helloworld.proto",
}

func init() { proto.RegisterFile("pb/helloworld.proto", fileDescriptor_helloworld_d130e9b83d1fb14f) }

var fileDescriptor_helloworld_d130e9b83d1fb14f = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x5d, 0x4b, 0xc3, 0x30,
	0x14, 0xb5, 0x20, 0x6e, 0x3b, 0xac, 0x53, 0xae, 0x20, 0x35, 0xee, 0x41, 0x82, 0x0c, 0x5f, 0x9c,
	0xa2, 0x08, 0x3e, 0xf9, 0xe8, 0x06, 0x8a, 0x0f, 0xf3, 0x17, 0x64, 0x78, 0xa7, 0x83, 0xcc, 0xd6,
	0xb4, 0x2a, 0xfb, 0xb7, 0xfe, 0x14, 0x49, 0x5d, 0x96, 0xa4, 0xce, 0xb7, 0xde, 0x73, 0xcf, 0x47,
	0x73, 0x12, 0xec, 0x17, 0xd3, 0xf3, 0x57, 0xd6, 0x3a, 0xff, 0xca, 0x8d, 0x7e, 0x1e, 0x16, 0x26,
	0xaf, 0x72, 0x82, 0x47, 0xe4, 0x05, 0xf6, 0xee, 0xe6, 0xa6, 0xac, 0x1e, 0xd5, 0x82, 0x27, 0xfc,
	0xfe, 0xc1, 0x65, 0x45, 0x7d, 0x74, 0x66, 0x0e, 0xcb, 0x92, 0xe3, 0xe4, 0xb4, 0x33, 0xf1, 0x80,
	0xbc, 0x41, 0x2f, 0x50, 0x14, 0x7a, 0x49, 0x03, 0xf4, 0x66, 0x11, 0xb2, 0x12, 0x35, 0x50, 0x79,
	0x86, 0xdd, 0x07, 0x15, 0x47, 0x09, 0xb4, 0xb5, 0x8a, 0x92, 0xd6, 0xb3, 0xbc, 0x46, 0xea, 0xe9,
	0x36, 0xe7, 0x04, 0xa9, 0x56, 0x7f, 0x63, 0x62, 0x50, 0x4a, 0x74, 0xc7, 0xf6, 0x7c, 0x2e, 0x82,
	0xb0, 0xfd, 0xe6, 0xed, 0xeb, 0x6f, 0x39, 0x00, 0x56, 0x1c, 0xeb, 0x9b, 0xa1, 0xb5, 0xe0, 0xb2,
	0x54, 0x2f, 0x8e, 0xe4, 0xc6, 0xcb, 0xef, 0x04, 0xad, 0x91, 0x61, 0xae, 0xd8, 0xd0, 0x2d, 0xda,
	0x4f, 0x6a, 0x59, 0xcb, 0x28, 0x1b, 0x06, 0xa5, 0x86, 0x69, 0xe2, 0x60, 0xc3, 0xc6, 0xfe, 0xd5,
	0x16, 0xdd, 0x23, 0x1d, 0xcd, 0x3f, 0x79, 0xdd, 0x1d, 0xf5, 0x43, 0x6a, 0xf3, 0x12, 0x84, 0xf8,
	0x67, 0xfb, 0x6b, 0x36, 0x46, 0xd7, 0x9a, 0xb9, 0x7e, 0xe8, 0x28, 0x64, 0x37, 0x4a, 0x16, 0x87,
	0x9b, 0x97, 0xb5, 0xd3, 0x74, 0xa7, 0x7e, 0x13, 0x57, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xdd,
	0xe1, 0x90, 0x99, 0x2a, 0x02, 0x00, 0x00,
}
